name: ğŸš€ Flet APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: pip install flet
    - run: flet build apk
    - uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: build/apk/**/*.apk
    - run: |
        echo "âœ… APK Built!"
        echo "â¬‡ï¸ Download from Artifacts below ğŸ‘‡"
